name: Release Workflow

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    if: "!contains(github.ref_name, '-beta')"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Create zip file
      run: |
        # 假设你想压缩整个仓库内容，排除.git和.github目录
        zip -r release.zip . -x "*.git*" "*.github*" "*.DS_Store"

    - name: 创建正式版 Release
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh release create "${{ github.ref_name }}" release.zip \
          --title "${{ github.ref_name }} 正式版" \
          --notes "正式版发布" \
          --latest
